version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fixiny_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/fixiny_db?schema=public"

  frontend:
    build: ./frontend/web
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
